name: Analysis

# Declare default permissions as read only.
permissions: read-all

on: [push, pull_request]
jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v6
      - name: set up JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Run detekt
        run: bash ./gradlew detekt
  spotless:
    name: Spotless (ktlint)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v6
      - name: set up JDK 21
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Run spotless
        run: bash ./gradlew spotlessCheck
